// AUTO-DERIVED icon registry — do not hand-edit lightly.
//
// Maps kebab-case names (as passed to <Icon name="..."> and <Button icon="...">)
// to explicitly-imported lucide-react components. The previous Icon component used
// `import * as Lucide` with a dynamic lookup, which forced the bundler to ship the
// entire ~1500-icon library in the entry chunk. Importing each icon by name lets the
// bundler tree-shake down to just the icons this app actually uses.
//
// To regenerate: extract every kebab-case string literal from src/ and keep the ones
// that resolve to a real lucide-react export (see scripts in PR history). Unknown
// names fall back to Circle in Icon.tsx, so a missing entry degrades gracefully.

import {
  Activity,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  AudioLines,
  Baby,
  BadgeHelp,
  BarChart3,
  Baseline,
  Book,
  BookOpen,
  Bot,
  BoxSelect,
  CalendarRange,
  Camera,
  Check,
  CheckCheck,
  ChevronLeft,
  ChevronRight,
  Circle,
  Clock,
  Columns3,
  Compass,
  Construction,
  Copy,
  Database,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  File,
  FileText,
  Filter,
  Flag,
  FunctionSquare,
  Ghost,
  GitBranch,
  GitCommit,
  GitFork,
  GitMerge,
  Grid,
  Grid3x3,
  Group,
  Heading,
  HeartHandshake,
  HeartPulse,
  Home,
  Image,
  Info,
  Kanban,
  LaptopMinimal,
  Layers,
  LayoutDashboard,
  Library,
  LineChart,
  Link,
  List,
  ListChecks,
  Map,
  Merge,
  MessageSquare,
  Milestone,
  Monitor,
  Moon,
  Mountain,
  Navigation,
  Network,
  Pause,
  PauseCircle,
  Pill,
  Play,
  Pointer,
  Presentation,
  Radio,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Save,
  Scale,
  ScatterChart,
  Scroll,
  Search,
  Send,
  ServerCog,
  Shell,
  ShieldCheck,
  Shrink,
  Shuffle,
  SkipBack,
  SkipForward,
  Sliders,
  Sparkles,
  Square,
  Sun,
  Table,
  Table2,
  TableCellsSplit,
  Tablet,
  Tag,
  Tags,
  Target,
  Terminal,
  Text,
  ThermometerSun,
  TriangleAlert,
  User,
  UserPlus,
  Verified,
  Video,
  Volume,
  WandSparkles,
  Watch,
  Waves,
  X,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  "activity": Activity,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "arrow-up-down": ArrowUpDown,
  "audio-lines": AudioLines,
  "baby": Baby,
  "badge-help": BadgeHelp,
  "bar-chart-3": BarChart3,
  "baseline": Baseline,
  "book": Book,
  "book-open": BookOpen,
  "bot": Bot,
  "box-select": BoxSelect,
  "calendar-range": CalendarRange,
  "camera": Camera,
  "check": Check,
  "check-check": CheckCheck,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "circle": Circle,
  "clock": Clock,
  "columns-3": Columns3,
  "compass": Compass,
  "construction": Construction,
  "copy": Copy,
  "database": Database,
  "download": Download,
  "ellipsis": Ellipsis,
  "external-link": ExternalLink,
  "eye": Eye,
  "file": File,
  "file-text": FileText,
  "filter": Filter,
  "flag": Flag,
  "function-square": FunctionSquare,
  "ghost": Ghost,
  "git-branch": GitBranch,
  "git-commit": GitCommit,
  "git-fork": GitFork,
  "git-merge": GitMerge,
  "grid": Grid,
  "grid-3x3": Grid3x3,
  "group": Group,
  "heading": Heading,
  "heart-handshake": HeartHandshake,
  "heart-pulse": HeartPulse,
  "home": Home,
  "image": Image,
  "info": Info,
  "kanban": Kanban,
  "laptop-minimal": LaptopMinimal,
  "layers": Layers,
  "layout-dashboard": LayoutDashboard,
  "library": Library,
  "line-chart": LineChart,
  "link": Link,
  "list": List,
  "list-checks": ListChecks,
  "map": Map,
  "merge": Merge,
  "message-square": MessageSquare,
  "milestone": Milestone,
  "monitor": Monitor,
  "moon": Moon,
  "mountain": Mountain,
  "navigation": Navigation,
  "network": Network,
  "pause": Pause,
  "pause-circle": PauseCircle,
  "pill": Pill,
  "play": Play,
  "pointer": Pointer,
  "presentation": Presentation,
  "radio": Radio,
  "refresh-cw": RefreshCw,
  "rotate-ccw": RotateCcw,
  "rotate-cw": RotateCw,
  "save": Save,
  "scale": Scale,
  "scatter-chart": ScatterChart,
  "scroll": Scroll,
  "search": Search,
  "send": Send,
  "server-cog": ServerCog,
  "shell": Shell,
  "shield-check": ShieldCheck,
  "shrink": Shrink,
  "shuffle": Shuffle,
  "skip-back": SkipBack,
  "skip-forward": SkipForward,
  "sliders": Sliders,
  "sparkles": Sparkles,
  "square": Square,
  "sun": Sun,
  "table": Table,
  "table-2": Table2,
  "table-cells-split": TableCellsSplit,
  "tablet": Tablet,
  "tag": Tag,
  "tags": Tags,
  "target": Target,
  "terminal": Terminal,
  "text": Text,
  "thermometer-sun": ThermometerSun,
  "triangle-alert": TriangleAlert,
  "user": User,
  "user-plus": UserPlus,
  "verified": Verified,
  "video": Video,
  "volume": Volume,
  "wand-sparkles": WandSparkles,
  "watch": Watch,
  "waves": Waves,
  "x": X,
};

/** Guaranteed-defined fallback for unknown icon names. */
export const FALLBACK_ICON: LucideIcon = Circle;
