#!/usr/bin/env python3
"""Build and register `esd-buddy`: this lab's tuned local model.

The base model alone is not a configuration. Thread count, context window, stop
sequences, sampling and the grounding contract all have to be pinned somewhere
reproducible, and passing them per-request does not work through the
OpenAI-compatible endpoint the provider chain speaks -- `num_thread` and
`num_ctx` are load-time properties of the runner, not request parameters.

So this generates an Ollama Modelfile, builds a derived model named `esd-buddy`
from it, and points the runtime at that name. The Modelfile is written into the
repository, so the exact configuration serving answers is reviewable in a diff
rather than living in someone's shell history.

    python scripts/sync_local_model.py                  # plan only
    python scripts/sync_local_model.py --apply          # build + register
    python scripts/sync_local_model.py --apply --base qwen3:4b
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scripts.check_gpu_runtime import build_report  # noqa: E402

MODELFILE_PATH = PROJECT_ROOT / "config" / "esd-buddy.Modelfile"
CONFIG_PATH = PROJECT_ROOT / "config" / "llm_model.json"
MODEL_NAME = "esd-buddy"
OLLAMA_URL = os.environ.get("ESD_OLLAMA_URL", "http://127.0.0.1:11434")

#: The grounding contract, baked into the model rather than prepended per call.
#: Keeping it here means every caller gets it, including anything that talks to
#: Ollama directly, and it cannot be dropped by a prompt-assembly bug.
SYSTEM_PROMPT = """\
You are the ESD Lab buddy. You answer questions about the Early Social Development \
Lab at the University of South Carolina and its studies: NANO, NICO, IPSA, ACTION and ABC.

Rules you follow without exception:
- Answer only from the CONTEXT you are given. The context is retrieved from the \
lab's own documents and aggregate data artifacts.
- Never state a number that does not appear in the context. If you are asked for a \
figure the context does not contain, say plainly that you do not have it.
- Never provide participant-level, identifiable, or raw-signal data. That stays in \
REDCap and the secure server. Offer the aggregate question you can answer instead.
- Cite what you used by naming the source file from the context.
- If the context does not answer the question, say so. Do not speculate and do not \
fill the gap from memory.

How you speak: present tense, active, first person. Precise and warm, never chirpy. \
No exclamation points on numbers. Say "I don't have that" without apology or padding."""


def ollama_bin() -> str:
    local = Path.home() / ".local" / "ollama" / "bin" / "ollama"
    if local.exists():
        return str(local)
    import shutil

    return shutil.which("ollama") or "ollama"


def installed_models() -> list[str]:
    try:
        with urllib.request.urlopen(f"{OLLAMA_URL}/api/tags", timeout=10) as r:  # noqa: S310
            return [m["name"] for m in json.load(r).get("models", [])]
    except (urllib.error.URLError, TimeoutError, OSError, json.JSONDecodeError):
        return []


def choose_base(explicit: str | None, plan: dict[str, Any], present: list[str]) -> str | None:
    """Pick the base model to derive from.

    An explicit choice wins. Otherwise take the benchmark's winner if one has
    been recorded, and fall back to the runtime plan's generalist.
    """
    if explicit:
        return explicit
    benchmark = PROJECT_ROOT / "config" / "model_benchmark.json"
    if benchmark.exists():
        try:
            winner = json.loads(benchmark.read_text(encoding="utf-8")).get("winner")
        except (OSError, json.JSONDecodeError):
            winner = None
        if winner and winner in present:
            return winner
    generalist = plan.get("generalist")
    return generalist if generalist in present else (present[0] if present else None)


def render_modelfile(base: str, plan: dict[str, Any]) -> str:
    threads = plan.get("num_thread", 8)
    context = 8192 if plan["tier"] == "cpu" else 32768
    return f"""\
# ESD Lab buddy -- generated by scripts/sync_local_model.py. Do not edit by hand.
#
# Derived from {base} for the {plan['tier'].upper()} tier on this host.
# Rebuild with: make model-sync
FROM {base}

# Load-time runner properties. These cannot be set per request through the
# OpenAI-compatible endpoint, which is why this model exists at all.
PARAMETER num_thread {threads}
PARAMETER num_ctx {context}

# Grounded lookup, not creative writing: low temperature keeps the answer close
# to the retrieved text, which is what makes citations honest.
PARAMETER temperature 0.2
PARAMETER top_p 0.9
PARAMETER repeat_penalty 1.05

SYSTEM \"\"\"{SYSTEM_PROMPT}\"\"\"
"""


def build_model(modelfile: Path) -> tuple[bool, str]:
    try:
        proc = subprocess.run(  # noqa: S603
            [ollama_bin(), "create", MODEL_NAME, "-f", str(modelfile)],
            cwd=PROJECT_ROOT, capture_output=True, text=True, timeout=900, check=False,
            env={**os.environ, "OLLAMA_HOST": OLLAMA_URL.replace("http://", "")},
        )
        return proc.returncode == 0, ((proc.stdout or "") + (proc.stderr or "")).strip()[-400:]
    except (subprocess.TimeoutExpired, OSError) as exc:
        return False, str(exc)


def smoke_test() -> tuple[bool, str]:
    """One real grounded question through the derived model."""
    body = json.dumps({
        "model": MODEL_NAME,
        "messages": [{
            "role": "user",
            "content": "CONTEXT:\n[entities.md]\nTarget N: 260 infants. Short name: NANO.\n\n"
                       "QUESTION: What is the NANO target sample size?",
        }],
        "stream": False,
        "options": {"num_predict": 60},
        "think": False,
    }).encode("utf-8")
    request = urllib.request.Request(
        f"{OLLAMA_URL}/api/chat", data=body, headers={"Content-Type": "application/json"}
    )
    try:
        with urllib.request.urlopen(request, timeout=300) as response:  # noqa: S310
            answer = (json.load(response).get("message") or {}).get("content", "").strip()
    except (urllib.error.URLError, TimeoutError, OSError, json.JSONDecodeError) as exc:
        return False, f"{type(exc).__name__}: {exc}"
    return ("260" in answer), answer[:160].replace("\n", " ")


def update_config(base: str, plan: dict[str, Any]) -> None:
    config = json.loads(CONFIG_PATH.read_text(encoding="utf-8")) if CONFIG_PATH.exists() else {}
    local = config.setdefault("local", {})
    local["serving_model"] = MODEL_NAME
    local["serving_base"] = base
    local["serving_tier"] = plan["tier"]
    local["num_thread"] = plan.get("num_thread")
    local["modelfile"] = str(MODELFILE_PATH.relative_to(PROJECT_ROOT))
    CONFIG_PATH.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--base", default=None, help="base model to derive from")
    parser.add_argument("--apply", action="store_true", help="build and register the model")
    args = parser.parse_args(argv)

    plan = build_report()["plan"]
    present = installed_models()
    if not present:
        print(f"Ollama is not reachable at {OLLAMA_URL}.", file=sys.stderr)
        return 1

    base = choose_base(args.base, plan, [m for m in present if "embed" not in m and m != f"{MODEL_NAME}:latest"])
    if not base:
        print("No base model installed. Run `make models-pull` first.", file=sys.stderr)
        return 1

    modelfile = render_modelfile(base, plan)
    print(f"  tier      {plan['tier']}")
    print(f"  base      {base}")
    print(f"  threads   {plan.get('num_thread')}")
    print(f"  target    {MODEL_NAME}")

    if not args.apply:
        print("\n--- Modelfile (dry run; pass --apply to build) ---")
        print(modelfile)
        return 0

    MODELFILE_PATH.parent.mkdir(parents=True, exist_ok=True)
    MODELFILE_PATH.write_text(modelfile, encoding="utf-8")
    print(f"\n  wrote {MODELFILE_PATH.relative_to(PROJECT_ROOT)}")

    ok, detail = build_model(MODELFILE_PATH)
    if not ok:
        print(f"  build FAILED: {detail}", file=sys.stderr)
        return 1
    print(f"  built {MODEL_NAME}")

    passed, answer = smoke_test()
    print(f"  smoke {'ok' if passed else 'FAILED'}: {answer}")
    if not passed:
        return 1

    update_config(base, plan)
    print(f"  updated {CONFIG_PATH.relative_to(PROJECT_ROOT)}")
    print(f"\n  Point the runtime at it with DASHBOARD_ASSISTANT_LOCAL_MODEL={MODEL_NAME}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
